testingggg

diff --git a/.github/workflows/reusable-plan.yml b/.github/workflows/reusable-plan.yml
--- a/.github/workflows/reusable-plan.yml
+++ b/.github/workflows/reusable-plan.yml
@@ -20,7 +20,7 @@ on:
 
 jobs:
   # This workflow contains a single job called "plan"
-  plan:
+  cdk-plan:
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
@@ -47,10 +47,14 @@ jobs:
         run: |
           npm run build
           cdk diff ${{ inputs.STACK }}
-  hold:
-    if: needs.plan.result == 'success' && github.event_name == 'push'
+      # If plan fails
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+  cdk-hold:
+    if: needs.cdk-plan.result == 'success' && github.event_name == 'push'
     runs-on: ubuntu-latest
-    needs: plan
+    needs: cdk-plan
     environment:
       name: ${{ inputs.ENV }}
     steps:
